-- 코드를 입력하세요
SELECT * FROM (
    SELECT 
        C.CAR_ID CAR_ID,
        C.CAR_TYPE CAR_TYPE,
        (DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100)) FEE
    FROM CAR_RENTAL_COMPANY_CAR C 
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE=P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND DURATION_TYPE='30일 이상'
    AND NOT EXISTS (
            SELECT 1 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            WHERE C.CAR_ID=H.CAR_ID 
            AND START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
    ) 
) T 
WHERE FEE >= 500000 AND FEE < 2000000 
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
    
    

