-- 코드를 작성해주세요
WITH RECURSIVE GENERATION_TREE AS (
    SELECT 
        ID, 
        PARENT_ID, 
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
        E.ID ID,
        E.PARENT_ID PARENT_ID,
        G.GENERATION + 1 AS GENERATION
    FROM
        ECOLI_DATA E
        JOIN GENERATION_TREE G 
        ON E.PARENT_ID=G.ID
)
SELECT 
    COUNT(*) COUNT,
    GENERATION
FROM GENERATION_TREE G
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA E
    WHERE G.ID=E.PARENT_ID
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;