-- 코드를 입력하세요
WITH NEW_PLACES AS (
    SELECT ID, 
        NAME,
        HOST_ID,
        COUNT(ID) OVER (PARTITION BY HOST_ID) PLACES_CNT
    FROM PLACES
)
SELECT ID, NAME, HOST_ID
FROM NEW_PLACES
WHERE PLACES_CNT > 1
ORDER BY ID;