-- 코드를 작성해주세요
WITH NEW_ECOLI AS (
    SELECT ID, 
        SIZE_OF_COLONY, 
        DIFFERENTIATION_DATE,
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) MAX_COLONY
    FROM ECOLI_DATA
)
SELECT YEAR(DIFFERENTIATION_DATE) YEAR, 
    MAX_COLONY - SIZE_OF_COLONY YEAR_DEV,
    ID
FROM NEW_ECOLI
ORDER BY YEAR, YEAR_DEV;